### ISSUE TITLE
Readable Output

### ISSUE THREAD

**Issue by Qoraiche** [ReeceM/mocker#1]
Hi, 
First, I want to say thank you for creating this Mock class,

It would be great if you make the mocked arguments output more user readable and complex, so we can use it within MailEclipse previews.

https://github.com/ReeceM/mocker/blob/73a2854e0ee83b24475c312256532fabdc4bdf43/src/Mocked.php#L39

This line returns a simple string `mocked varname`.

Needed Result:

`{{ varname }}`

Including `$vars` when defined:

`{{ varname->complex->var }}`

Thanks,
qoraiche.

**Comment by ReeceM** [comment]
Hi @Quraiche, thank you for the suggestion. I will have a look at making this work and also be flexible.

Just want to check, when you say the format would `{{ varname }}` it would be the actual _blade-like_  result that would be there or a value that would be replaceable by the blade render?

**Comment by Qoraiche** [comment]
> Hi @Quraiche, thank you for the suggestion. I will have a look at making this work and also be flexible.
> 
> Just want to check, when you say the format would `{{ varname }}` it would be the actual _blade-like_ result that would be there or a value that would be replaceable by the blade render?

I add the curly brackets just for clarification, not needed.

**Comment by ReeceM** [comment]
@Qoraiche :+1: 
:grinning:

**Comment by ReeceM** [comment]
Hi @Qoraiche, I have created a feature branch for the test of this feature. 

you can test it on the dev-v1 branch of the MailEclipse Package (thank you for the package too actually). 

You can use the dev-feature/readable_output branch for testing with the changes.

`composer require reecem/mocker:dev-feature/readable_output`

## Using

```php
// The initial call is the same for the mailEclipse.php
$mock = new ReflectionMockery($reflection);
        
/**
 * When assigning an untyped arg you can use the php magic method, or ->$arg
 */
$arg = 'data';

$filteredparams[] = $mock->get($arg);
// or 
$filteredparams[] = $mock->$arg;

// mailable.blade.php

{{ $data->comment }}  =>  data->comment

```

If during the Mailable's constructor or handle method and that it modifies the params passed, if the param is of type Mocker\Mocked then it will keep the set value.

```php
...

public function __construct(Mocked $user, $data)
{
    $data->complex->var->that->is->set->too = "Hello World";
    ...
    $this->bData = $data->complex->var->that->is->set->too;
}

...
// if the resulting variable is called $bData
// output would be without single quotes
'data->complex->var->that->is->set->too = "Hello World"'

```

**Comment by ReeceM** [comment]
In hind site, I may make it return only the set value when a __set() is called on a mock class, probably won't break classes.

**Comment by ReeceM** [comment]
Hi @Qoraiche, please have a look at version 1.1.0 of the repo and let me know if this is along the lines of what you were looking for?

**Comment by Qoraiche** [comment]
@ReeceM sorry for late I have some personal problems, so yes it's 100% what I'm looking for, thanks!

**Comment by Qoraiche** [comment]
I afraid that I don't have time to commit into Maileclipse, I would be thankful if you can open a new PR into the master branch adding all needed changes.

1. Require `ReeceM/mocker`.
2. Integrate mocker functionality.

**Comment by ReeceM** [comment]
@Qoraiche, I will open a PR, I only saw this now too. 
Sorry I wasn't trying to rush you if you are busy.

**Comment by Qoraiche** [comment]
@ReeceM no it's okay, I like your work btw.
