### ISSUE TITLE
Reach author

### ISSUE THREAD

**Issue by Qoraiche** [ReeceM/mocker#11]
Hey @ReeceM, how can i reach you? email, slack?

**Comment by ReeceM** [comment]
Hi @Qoraiche, I usually use email for most communication. 

I have slack as well.

**Comment by Qoraiche** [comment]
@ReeceM can you share it with me so I can add you to my slack channel?

**Comment by ReeceM** [comment]
Hi @Qoraiche, it is reecestevenmay@gmail.com

**Comment by Qoraiche** [comment]
Invitation Sent! check your email

**Comment by ReeceM** [comment]
Got it, 👍
