### ISSUE TITLE
Add Laravel 7 Support

### ISSUE THREAD

**Issue by blakehooks** [ReeceM/mocker#12]
**Is your feature request related to a problem? Please describe.**
Package currently does not support Laravel 7, blocking the ability to upgrade for any projects that use this library directly or any packages that require this library.

**Describe the solution you'd like**
Add support for illuminate/filesystem to ^7.0

**Describe alternatives you've considered**
Only possible alternative is to remove any package that requires this library

**Comment by blakehooks** [comment]
Can be fixed with https://github.com/ReeceM/mocker/pull/13

**Comment by Qoraiche** [comment]
@ReeceM could you check this out

**Comment by ReeceM** [comment]
@Qoraiche and @blakehooks thank you both for bringing it to my attention. Forgot this
