### ISSUE TITLE
Pollution across the objects and array values from VarStrore::class

### ISSUE THREAD

**Issue by ReeceM** [ReeceM/mocker#6]
**Describe the bug**
There is the definite chance that a value set on a different object will be returned when it is retrieved from a different one that doesn't come from the same call

**To Reproduce**
```php
// assign a value to the mocker object
$mocked->value1->sub_value = 2;

echo $mocked->value1->sub_value . PHP_EOL;
// returns int(2)

// now assign that same sub_value to another object or array
$mocked->assoc_arr['sub_value'] = 'Must be different value';

echo $mocked->assoc_arr['sub_value'];
// returns 2

// but

echo $mocked->sub_value; 
// returns 2

echo $mocked->value1->sub_value; 
// returns 2
```

**Expected behavior**
This should not do that and has a problem to do with the flat structure of the VarStore and the way in which the values are resolved. 

The VarStore should be structured as the way in which the values should be called i.e.:

```php
// calling 
$mocked->sub_value; // would return 'null' or 'mocked->sub_value';
or
$mocked->value1->sub_value; // gives 2
and 
$mocked->assoc_arr['sub_value']; // will give the string
```

**Comment by Qoraiche** [comment]
Interesting
