### ISSUE TITLE
Maileclipse - Laravel 6

### ISSUE THREAD

**Issue by Qoraiche** [ReeceM/mocker#9]
Hello,
Does this package still working with Maileclipse on laravel 6? 

Thanks,

**Comment by ReeceM** [comment]
@Qoraiche, I will have a look as I haven't tested it yet.

**Comment by Qoraiche** [comment]
@ReeceM thanks, please consider PR to maileclipse when needed.

**Comment by ReeceM** [comment]
@Qoraiche, I have updated the dependencies for laravel 6 on this and it does work. I haven't made it a feature update to the version as I accounted for v5/6 of laravel.

I did notice it was removed from the latest PR on maileclipse repo, I did comment to the contributor of the PR that they could keep it there.

**Comment by Qoraiche** [comment]
@ReeceM great! thanks again

**Comment by Qoraiche** [comment]
I've closed the latest PR (https://github.com/Qoraiche/laravel-mail-editor/pull/49), can you please open a new PR for the new update?

Thanks,

**Comment by ReeceM** [comment]
@Qoraiche, I could do. I will just have to update local repo 👍

**Comment by ReeceM** [comment]
@Qoraiche, Do you want backwards compatibility?

**Comment by Qoraiche** [comment]
@ReeceM of course

**Comment by codepotato** [comment]
Just fixing at the moment chaps. Needed to rename a couple of bits locally to get this working but working now. Pushing up a new PR now

**Comment by Qoraiche** [comment]
@codepotato thanks, @ReeceM please review https://github.com/Qoraiche/laravel-mail-editor/pull/50.

thanks both of you.

**Comment by codepotato** [comment]
No problem at all!

**Comment by Qoraiche** [comment]
Guys don't forget to star @ReeceM repo ⭐️
